spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    username: root
    password: 123456

  redis:
    host: 192.168.170.128
  rabbitmq:
    host: 192.168.170.128
    username: admin
    password: admin
